"""initial schema

Revision ID: 6b2441ba68ca
Revises: 
Create Date: 2026-08-21 04:46:41.066338+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b2441ba68ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('health_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_heartbeat_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_last_heartbeat_at'), 'services', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_table('config_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=80), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_config_keys_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_keys')),
    sa.UniqueConstraint('service_id', 'key', name='uq_config_keys_service_key')
    )
    op.create_index(op.f('ix_config_keys_group'), 'config_keys', ['group'], unique=False)
    op.create_index(op.f('ix_config_keys_service_id'), 'config_keys', ['service_id'], unique=False)
    op.create_table('config_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_key_id', sa.String(length=36), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['config_key_id'], ['config_keys.id'], name=op.f('fk_config_history_config_key_id_config_keys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_history'))
    )
    op.create_index(op.f('ix_config_history_changed_at'), 'config_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_config_history_config_key_id'), 'config_history', ['config_key_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_history_config_key_id'), table_name='config_history')
    op.drop_index(op.f('ix_config_history_changed_at'), table_name='config_history')
    op.drop_table('config_history')
    op.drop_index(op.f('ix_config_keys_service_id'), table_name='config_keys')
    op.drop_index(op.f('ix_config_keys_group'), table_name='config_keys')
    op.drop_table('config_keys')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_index(op.f('ix_services_last_heartbeat_at'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###