"""initial schema

Revision ID: 464006dae93f
Revises: 
Create Date: 2026-08-21 04:05:54.877070+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464006dae93f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('mailboxes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mailboxes_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailboxes'))
    )
    op.create_index(op.f('ix_mailboxes_address'), 'mailboxes', ['address'], unique=True)
    op.create_index(op.f('ix_mailboxes_expires_at'), 'mailboxes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_mailboxes_user_id'), 'mailboxes', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mailbox_id', sa.String(length=36), nullable=False),
    sa.Column('rfc_message_id', sa.String(length=512), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('to_addresses', sa.Text(), nullable=False),
    sa.Column('cc_addresses', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('spam_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_messages_mailbox_id_mailboxes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_from_address'), 'messages', ['from_address'], unique=False)
    op.create_index(op.f('ix_messages_mailbox_id'), 'messages', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_messages_received_at'), 'messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_messages_rfc_message_id'), 'messages', ['rfc_message_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_messages_rfc_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_received_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_mailbox_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_address'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_mailboxes_user_id'), table_name='mailboxes')
    op.drop_index(op.f('ix_mailboxes_expires_at'), table_name='mailboxes')
    op.drop_index(op.f('ix_mailboxes_address'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###