"""add folders labels trash

Revision ID: 3bec893375c5
Revises: 57d92a72a315
Create Date: 2026-08-21 08:14:51.521257+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bec893375c5'
down_revision: Union[str, None] = '57d92a72a315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_folders_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.create_index(op.f('ix_folders_owner_id'), 'folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_folders_slug'), 'folders', ['slug'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_labels_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels'))
    )
    op.create_index(op.f('ix_labels_owner_id'), 'labels', ['owner_id'], unique=False)
    op.create_table('message_labels',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('label_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_message_labels_label_id_labels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_labels_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'label_id', name=op.f('pk_message_labels'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('is_trashed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(op.f('ix_messages_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(op.f('ix_messages_is_trashed'), ['is_trashed'], unique=False)
        batch_op.create_foreign_key(op.f('fk_messages_folder_id_folders'), 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ===== PostgreSQL-only: full-text search column =====
    # This is a no-op on SQLite; we apply it lazily at startup via
    # search_service.ensure_search_index() if the DB is PostgreSQL.
    # Keeping it commented keeps the migration portable.
    # op.execute("ALTER TABLE messages ADD COLUMN IF NOT EXISTS search_tsv tsvector")
    # op.execute("CREATE INDEX IF NOT EXISTS ix_messages_search_tsv ON messages USING GIN (search_tsv)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_messages_folder_id_folders'), type_='foreignkey')
    op.drop_index(op.f('ix_messages_is_trashed'), table_name='messages')
    op.drop_index(op.f('ix_messages_folder_id'), table_name='messages')
    op.drop_column('messages', 'trashed_at')
    op.drop_column('messages', 'is_trashed')
    op.drop_column('messages', 'folder_id')
    op.drop_table('message_labels')
    op.drop_index(op.f('ix_labels_owner_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_folders_slug'), table_name='folders')
    op.drop_index(op.f('ix_folders_owner_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###