"""LLM provider + model catalog (international + China + proxy providers).

This module is the single source of truth for the *static* part of the AI
configuration: which providers exist, where to call them, and which models
they offer. Only the per-provider API key + the currently active
provider/model are persisted at runtime (handled by the ai-service via
config-service). Adding a new provider here does NOT require any code
changes elsewhere.

The vast majority of modern LLM providers expose an OpenAI-compatible
/chat/completions endpoint. We use that as the default api_style.
A handful of providers (Anthropic) ship their own request format; we
expose them under a separate api_style="anthropic" flag for the client
to dispatch correctly.
"""
from __future__ import annotations

from typing import List, Dict, Any


PROVIDERS: List[Dict[str, Any]] = [

    # International
    {"id": "openai", "name": "OpenAI", "name_en": "OpenAI", "region": "global", "description": "ChatGPT 背后的公司，GPT 系列模型。", "base_url": "https://api.openai.com/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://platform.openai.com/docs", "signup_url": "https://platform.openai.com/api-keys", "models": [{"id": "gpt-4o", "name": "GPT-4o", "description": "多模态旗舰，对话/图像/音频。", "context_window": 128000, "max_output": 16384, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["flagship", "multimodal"]}, {"id": "gpt-4o-mini", "name": "GPT-4o mini", "description": "更快更便宜的多模态模型。", "context_window": 128000, "max_output": 16384, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["fast", "multimodal"]}, {"id": "gpt-4-turbo", "name": "GPT-4 Turbo", "description": "上一代主力，长上下文。", "context_window": 128000, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["legacy"]}, {"id": "gpt-4", "name": "GPT-4", "description": "经典 GPT-4。", "context_window": 8192, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["legacy"]}, {"id": "gpt-3.5-turbo", "name": "GPT-3.5 Turbo", "description": "经济型对话模型。", "context_window": 16385, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}, {"id": "o1", "name": "o1", "description": "强推理模型，慢但准。", "context_window": 200000, "max_output": 100000, "supports_streaming": True, "supports_vision": True, "supports_tools": False, "tags": ["reasoning"]}, {"id": "o1-mini", "name": "o1 mini", "description": "轻量推理模型。", "context_window": 128000, "max_output": 65536, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["reasoning", "cheap"]}, {"id": "o1-preview", "name": "o1 preview", "description": "o1 早期预览。", "context_window": 128000, "max_output": 32768, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["reasoning", "preview"]}, {"id": "o3-mini", "name": "o3-mini", "description": "o3 系列轻量版。", "context_window": 200000, "max_output": 100000, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["reasoning"]}, {"id": "o4-mini", "name": "o4-mini", "description": "最新轻量推理模型。", "context_window": 200000, "max_output": 100000, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["reasoning", "new"]}]},
    {"id": "anthropic", "name": "Anthropic (Claude)", "name_en": "Anthropic Claude", "region": "global", "description": "Claude 系列，擅长长文档与代码。", "base_url": "https://api.anthropic.com/v1", "api_style": "anthropic", "auth_header": "x-api-key", "auth_prefix": "", "doc_url": "https://docs.anthropic.com", "signup_url": "https://console.anthropic.com", "models": [{"id": "claude-3-5-sonnet-latest", "name": "Claude 3.5 Sonnet", "description": "主力推理与代码模型。", "context_window": 200000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["flagship"]}, {"id": "claude-3-5-haiku-latest", "name": "Claude 3.5 Haiku", "description": "高速版。", "context_window": 200000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast"]}, {"id": "claude-3-opus-20240229", "name": "Claude 3 Opus", "description": "深度推理旗舰。", "context_window": 200000, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["legacy"]}, {"id": "claude-3-sonnet-20240229", "name": "Claude 3 Sonnet", "description": "平衡型。", "context_window": 200000, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["legacy"]}, {"id": "claude-3-haiku-20240307", "name": "Claude 3 Haiku", "description": "轻量快速。", "context_window": 200000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}]},
    {"id": "gemini", "name": "Google Gemini", "name_en": "Google Gemini", "region": "global", "description": "Google 多模态大模型，提供 OpenAI 兼容端点。", "base_url": "https://generativelanguage.googleapis.com/v1beta/openai", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://ai.google.dev/gemini-api/docs/openai", "signup_url": "https://aistudio.google.com/apikey", "models": [{"id": "gemini-2.0-flash-exp", "name": "Gemini 2.0 Flash", "description": "实验版下一代 Flash。", "context_window": 1000000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["new", "fast"]}, {"id": "gemini-1.5-pro", "name": "Gemini 1.5 Pro", "description": "深度推理主力。", "context_window": 2000000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["flagship"]}, {"id": "gemini-1.5-flash", "name": "Gemini 1.5 Flash", "description": "高速轻量。", "context_window": 1000000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["fast"]}, {"id": "gemini-1.5-flash-8b", "name": "Gemini 1.5 Flash-8B", "description": "超轻量。", "context_window": 1000000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["cheap"]}]},
    {"id": "mistral", "name": "Mistral AI", "name_en": "Mistral AI", "region": "global", "description": "法国 Mistral 开源系列商业服务。", "base_url": "https://api.mistral.ai/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://docs.mistral.ai", "signup_url": "https://console.mistral.ai", "models": [{"id": "mistral-large-latest", "name": "Mistral Large", "description": "旗舰推理。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "mistral-medium-latest", "name": "Mistral Medium", "description": "中端。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "mistral-small-latest", "name": "Mistral Small", "description": "轻量。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast"]}, {"id": "codestral-latest", "name": "Codestral", "description": "代码专用。", "context_window": 32000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["code"]}, {"id": "ministral-8b-latest", "name": "Ministral 8B", "description": "超轻量端侧模型。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}]},
    {"id": "xai", "name": "xAI (Grok)", "name_en": "xAI Grok", "region": "global", "description": "马斯克的 xAI，提供 Grok 系列。", "base_url": "https://api.x.ai/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://docs.x.ai", "signup_url": "https://console.x.ai", "models": [{"id": "grok-2-latest", "name": "Grok 2", "description": "旗舰对话模型。", "context_window": 131072, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["flagship"]}, {"id": "grok-2-mini", "name": "Grok 2 mini", "description": "轻量。", "context_window": 131072, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast"]}, {"id": "grok-beta", "name": "Grok Beta", "description": "测试版。", "context_window": 131072, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["preview"]}]},
    {"id": "groq", "name": "Groq", "name_en": "Groq", "region": "global", "description": "超低延迟 LPU 推理，托管开源大模型。", "base_url": "https://api.groq.com/openai/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://console.groq.com/docs/openai", "signup_url": "https://console.groq.com", "models": [{"id": "llama-3.3-70b-versatile", "name": "Llama 3.3 70B", "description": "Meta 开源旗舰。", "context_window": 128000, "max_output": 32768, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source", "fast"]}, {"id": "llama-3.1-8b-instant", "name": "Llama 3.1 8B", "description": "极快轻量。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast", "cheap"]}, {"id": "mixtral-8x7b-32768", "name": "Mixtral 8x7B", "description": "MoE 架构。", "context_window": 32768, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}, {"id": "gemma2-9b-it", "name": "Gemma 2 9B", "description": "Google 开源小模型。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["open-source", "cheap"]}]},
    {"id": "cohere", "name": "Cohere", "name_en": "Cohere", "region": "global", "description": "企业级 RAG 与工具调用强项。", "base_url": "https://api.cohere.com/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://docs.cohere.com", "signup_url": "https://dashboard.cohere.com", "models": [{"id": "command-r-plus", "name": "Command R+", "description": "主力长文档/RAG。", "context_window": 128000, "max_output": 4000, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["rag"]}, {"id": "command-r", "name": "Command R", "description": "经济型。", "context_window": 128000, "max_output": 4000, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}, {"id": "command-light", "name": "Command Light", "description": "轻量对话。", "context_window": 4096, "max_output": 4000, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["cheap"]}]},
    {"id": "together", "name": "Together AI", "name_en": "Together AI", "region": "global", "description": "托管大量开源模型。", "base_url": "https://api.together.xyz/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://docs.together.ai", "signup_url": "https://api.together.xyz", "models": [{"id": "meta-llama/Llama-3.3-70B-Instruct-Turbo", "name": "Llama 3.3 70B Instruct", "description": "Meta 旗舰开源。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}, {"id": "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo", "name": "Llama 3.2 90B Vision", "description": "开源多模态。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": False, "tags": ["open-source", "vision"]}, {"id": "Qwen/Qwen2.5-72B-Instruct-Turbo", "name": "Qwen 2.5 72B Instruct", "description": "阿里通义开源旗舰。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}, {"id": "deepseek-ai/DeepSeek-V3", "name": "DeepSeek V3", "description": "DeepSeek 开源旗舰。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}]},

    # China (domestic) providers
    {"id": "deepseek", "name": "DeepSeek", "name_en": "DeepSeek", "region": "china", "description": "深度求索，国产高性价比对话/推理。", "base_url": "https://api.deepseek.com/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://platform.deepseek.com/docs", "signup_url": "https://platform.deepseek.com", "models": [{"id": "deepseek-chat", "name": "DeepSeek-V3 Chat", "description": "通用对话主力。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "deepseek-reasoner", "name": "DeepSeek-R1", "description": "深度推理模型（R1）。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["reasoning"]}, {"id": "deepseek-coder", "name": "DeepSeek-Coder", "description": "代码专用（V2 之前版本）。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["code", "legacy"]}]},
    {"id": "qwen", "name": "通义千问 (Qwen)", "name_en": "Alibaba Qwen (DashScope)", "region": "china", "description": "阿里云通义大模型，OpenAI 兼容端点。", "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://help.aliyun.com/zh/model-studio", "signup_url": "https://bailian.console.aliyun.com", "models": [{"id": "qwen-max", "name": "Qwen Max", "description": "通义最强模型。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "qwen-plus", "name": "Qwen Plus", "description": "性能/价格平衡。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "qwen-turbo", "name": "Qwen Turbo", "description": "高速轻量。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast"]}, {"id": "qwen-long", "name": "Qwen Long", "description": "超长上下文。", "context_window": 1000000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["long-context"]}, {"id": "qwq-32b-preview", "name": "QwQ-32B Preview", "description": "通义推理模型预览。", "context_window": 32000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["reasoning"]}, {"id": "qwen-vl-max", "name": "Qwen VL Max", "description": "通义视觉语言大模型（专用端点）。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": False, "tags": ["vision"]}]},
    {"id": "zhipu", "name": "智谱 AI (GLM)", "name_en": "Zhipu GLM", "region": "china", "description": "智谱 GLM 系列，OpenAI 兼容端点。", "base_url": "https://open.bigmodel.cn/api/paas/v4", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://bigmodel.cn/dev", "signup_url": "https://bigmodel.cn", "models": [{"id": "glm-4-plus", "name": "GLM-4 Plus", "description": "智谱旗舰。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "glm-4-0520", "name": "GLM-4 0520", "description": "主力模型。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "glm-4", "name": "GLM-4", "description": "通用对话。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "glm-4-air", "name": "GLM-4 Air", "description": "经济型。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}, {"id": "glm-4-airx", "name": "GLM-4 AirX", "description": "更快响应。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast"]}, {"id": "glm-4-flash", "name": "GLM-4 Flash", "description": "免费高速。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["free", "fast"]}, {"id": "glm-4v-plus", "name": "GLM-4V Plus", "description": "视觉理解。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": False, "tags": ["vision"]}, {"id": "codegeex-4", "name": "CodeGeeX-4", "description": "代码专用。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["code"]}]},
    {"id": "moonshot", "name": "月之暗面 (Kimi)", "name_en": "Moonshot Kimi", "region": "china", "description": "Moonshot 长上下文 Kimi。", "base_url": "https://api.moonshot.cn/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://platform.moonshot.cn/docs", "signup_url": "https://platform.moonshot.cn", "models": [{"id": "moonshot-v1-8k", "name": "Moonshot v1 8K", "description": "8K 上下文。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "moonshot-v1-32k", "name": "Moonshot v1 32K", "description": "32K 上下文。", "context_window": 32768, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "moonshot-v1-128k", "name": "Moonshot v1 128K", "description": "128K 超长上下文。", "context_window": 131072, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["long-context"]}, {"id": "moonshot-v1-auto", "name": "Moonshot v1 Auto", "description": "自动选择合适规格。", "context_window": 131072, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["auto"]}, {"id": "kimi-k2-0711-preview", "name": "Kimi K2 Preview", "description": "K2 预览版，工具调用强。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["reasoning", "new"]}]},
    {"id": "baidu", "name": "百度文心一言", "name_en": "Baidu ERNIE", "region": "china", "description": "百度文心大模型，OpenAI 兼容端点（千帆）。", "base_url": "https://qianfan.baidubce.com/v2", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://cloud.baidu.com/doc/qianfan", "signup_url": "https://console.bce.baidu.com", "models": [{"id": "ernie-4.0-8k", "name": "ERNIE-4.0 8K", "description": "文心 4.0 旗舰。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "ernie-3.5-8k", "name": "ERNIE-3.5 8K", "description": "主力模型。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "ernie-3.5-128k", "name": "ERNIE-3.5 128K", "description": "长上下文版。", "context_window": 128000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["long-context"]}, {"id": "ernie-speed-8k", "name": "ERNIE-Speed 8K", "description": "高速模型。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["fast"]}, {"id": "ernie-lite-8k", "name": "ERNIE-Lite 8K", "description": "轻量经济。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["cheap"]}]},
    {"id": "doubao", "name": "字节豆包 (火山方舟)", "name_en": "ByteDance Doubao", "region": "china", "description": "字节跳动豆包大模型，火山引擎方舟。", "base_url": "https://ark.cn-beijing.volces.com/api/v3", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://www.volcengine.com/docs/82379", "signup_url": "https://www.volcengine.com", "models": [{"id": "doubao-pro-32k", "name": "Doubao Pro 32K", "description": "豆包主力 Pro 版。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "doubao-pro-256k", "name": "Doubao Pro 256K", "description": "超长上下文。", "context_window": 256000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["long-context"]}, {"id": "doubao-lite-32k", "name": "Doubao Lite 32K", "description": "轻量版。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}, {"id": "doubao-lite-128k", "name": "Doubao Lite 128K", "description": "轻量长上下文。", "context_window": 128000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap", "long-context"]}, {"id": "doubao-vision-pro-32k", "name": "Doubao Vision Pro", "description": "视觉理解模型。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": False, "tags": ["vision"]}]},
    {"id": "hunyuan", "name": "腾讯混元", "name_en": "Tencent Hunyuan", "region": "china", "description": "腾讯混元大模型，OpenAI 兼容端点。", "base_url": "https://hunyuan.tencent.com/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://cloud.tencent.com/document/product/1729", "signup_url": "https://cloud.tencent.com", "models": [{"id": "hunyuan-pro", "name": "Hunyuan Pro", "description": "混元旗舰。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "hunyuan-standard", "name": "Hunyuan Standard", "description": "标准版。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "hunyuan-lite", "name": "Hunyuan Lite", "description": "轻量经济。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["cheap"]}, {"id": "hunyuan-vision", "name": "Hunyuan Vision", "description": "视觉理解。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": True, "supports_tools": False, "tags": ["vision"]}]},
    {"id": "spark", "name": "讯飞星火", "name_en": "iFlytek Spark", "region": "china", "description": "科大讯飞星火大模型，OpenAI 兼容端点。", "base_url": "https://spark-api-open.xf-yun.com/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://www.xfyun.cn/doc/spark", "signup_url": "https://console.xfyun.cn", "models": [{"id": "4.0Ultra", "name": "Spark v4.0 Ultra", "description": "星火 4.0 Ultra 旗舰。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "generalv3.5", "name": "Spark v3.5", "description": "星火 3.5。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "generalv3", "name": "Spark v3.0", "description": "星火 3.0。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["legacy"]}]},
    {"id": "baichuan", "name": "百川智能", "name_en": "Baichuan", "region": "china", "description": "百川智能大模型。", "base_url": "https://api.baichuan-ai.com/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://platform.baichuan-ai.com/docs", "signup_url": "https://platform.baichuan-ai.com", "models": [{"id": "Baichuan4", "name": "Baichuan 4", "description": "百川 4 旗舰。", "context_window": 128000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["flagship"]}, {"id": "Baichuan3-Turbo", "name": "Baichuan 3 Turbo", "description": "高速轻量。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["fast"]}, {"id": "Baichuan3-Turbo-128k", "name": "Baichuan 3 Turbo 128K", "description": "长上下文。", "context_window": 128000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["long-context"]}]},
    {"id": "minimax", "name": "MiniMax", "name_en": "MiniMax", "region": "global", "description": "MiniMax abab 系列大模型（OpenAI 兼容）。", "base_url": "https://api.minimax.chat/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://api.minimax.chat", "signup_url": "https://api.minimax.chat", "models": [{"id": "abab6.5s-chat", "name": "abab 6.5s", "description": "MiniMax abab 系列对话模型。", "context_window": 245760, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "abab6.5-chat", "name": "abab 6.5", "description": "MiniMax abab 6.5。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "abab5.5s-chat", "name": "abab 5.5s", "description": "MiniMax abab 5.5s。", "context_window": 8192, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["cheap"]}]},


    # Proxy / aggregator / self-hosted providers
    {"id": "openrouter", "name": "OpenRouter", "name_en": "OpenRouter", "region": "proxy", "description": "聚合多家模型路由的 OpenAI 兼容服务。", "base_url": "https://openrouter.ai/api/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://openrouter.ai/docs", "signup_url": "https://openrouter.ai", "models": [{"id": "anthropic/claude-3.5-sonnet", "name": "Claude 3.5 Sonnet (via OpenRouter)", "description": "经 OpenRouter 路由。", "context_window": 200000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["flagship"]}, {"id": "openai/gpt-4o", "name": "GPT-4o (via OpenRouter)", "description": "经 OpenRouter 路由。", "context_window": 128000, "max_output": 16384, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["flagship"]}, {"id": "openai/gpt-4o-mini", "name": "GPT-4o mini (via OpenRouter)", "description": "经 OpenRouter 路由。", "context_window": 128000, "max_output": 16384, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["cheap"]}, {"id": "google/gemini-2.0-flash-exp:free", "name": "Gemini 2.0 Flash (free via OpenRouter)", "description": "免费实验版。", "context_window": 1000000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": ["free", "new"]}, {"id": "meta-llama/llama-3.3-70b-instruct:free", "name": "Llama 3.3 70B (free via OpenRouter)", "description": "免费开源模型。", "context_window": 128000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["free", "open-source"]}, {"id": "deepseek/deepseek-chat", "name": "DeepSeek V3 (via OpenRouter)", "description": "经 OpenRouter 路由。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}, {"id": "qwen/qwen-2.5-72b-instruct", "name": "Qwen 2.5 72B (via OpenRouter)", "description": "经 OpenRouter 路由。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}]},
    {"id": "siliconflow", "name": "硅基流动 (SiliconFlow)", "name_en": "SiliconFlow", "region": "proxy", "description": "国内托管开源模型的服务，OpenAI 兼容。", "base_url": "https://api.siliconflow.cn/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://docs.siliconflow.cn", "signup_url": "https://cloud.siliconflow.cn", "models": [{"id": "Qwen/Qwen2.5-72B-Instruct", "name": "Qwen 2.5 72B Instruct", "description": "通义开源旗舰。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}, {"id": "Qwen/Qwen2.5-32B-Instruct", "name": "Qwen 2.5 32B Instruct", "description": "通义 32B。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}, {"id": "Qwen/Qwen2.5-7B-Instruct", "name": "Qwen 2.5 7B Instruct", "description": "通义 7B 免费。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["free", "open-source"]}, {"id": "deepseek-ai/DeepSeek-V3", "name": "DeepSeek V3", "description": "DeepSeek 开源旗舰。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": ["open-source"]}, {"id": "deepseek-ai/DeepSeek-R1", "name": "DeepSeek R1", "description": "DeepSeek 推理模型。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["open-source", "reasoning"]}, {"id": "THUDM/glm-4-9b-chat", "name": "GLM-4 9B Chat", "description": "智谱开源版。", "context_window": 32000, "max_output": 4096, "supports_streaming": True, "supports_vision": False, "supports_tools": False, "tags": ["open-source"]}]},
    {"id": "oneapi", "name": "OneAPI (自部署中转)", "name_en": "OneAPI (self-hosted proxy)", "region": "proxy", "description": "开源大模型中转站（OneAPI / ChatGPT-Next-Web 等）。默认指向常见的本地/自托管地址，请按你的部署修改 base_url。", "base_url": "http://127.0.0.1:3000/v1", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "https://github.com/songquanpeng/one-api", "signup_url": "https://github.com/songquanpeng/one-api", "models": [{"id": "gpt-4o", "name": "GPT-4o", "description": "取决于 OneAPI 渠道配置。", "context_window": 128000, "max_output": 16384, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": []}, {"id": "claude-3-5-sonnet", "name": "Claude 3.5 Sonnet", "description": "取决于 OneAPI 渠道配置。", "context_window": 200000, "max_output": 8192, "supports_streaming": True, "supports_vision": True, "supports_tools": True, "tags": []}, {"id": "deepseek-chat", "name": "DeepSeek V3", "description": "取决于 OneAPI 渠道配置。", "context_window": 64000, "max_output": 8192, "supports_streaming": True, "supports_vision": False, "supports_tools": True, "tags": []}]},
    {"id": "custom", "name": "自定义 OpenAI 兼容端点", "name_en": "Custom OpenAI-compatible", "region": "proxy", "description": "任意 OpenAI 兼容服务（自托管 / 中转 / API2D / CloseAI 等）。请在设置中填入正确的 base_url 与模型 ID。", "base_url": "", "api_style": "openai", "auth_header": "Authorization", "auth_prefix": "Bearer ", "doc_url": "", "signup_url": "", "models": []},
]


# ----- Convenience helpers (pure-Python so no extra deps) -----


def list_providers() -> List[Dict[str, Any]]:
    return list(PROVIDERS)


def get_provider(provider_id: str):
    for p in PROVIDERS:
        if p["id"] == provider_id:
            return p
    return None


def list_models(provider_id: str) -> List[Dict[str, Any]]:
    p = get_provider(provider_id)
    return list(p["models"]) if p else []


def get_model(provider_id: str, model_id: str):
    for m in list_models(provider_id):
        if m["id"] == model_id:
            return m
    return None


def to_catalog_dict() -> Dict[str, Any]:
    """Compact, frontend-friendly representation of the catalog."""
    return {
        "providers": [
            {
                "id": p["id"],
                "name": p["name"],
                "name_en": p["name_en"],
                "region": p["region"],
                "description": p["description"],
                "base_url": p["base_url"],
                "api_style": p["api_style"],
                "auth_header": p["auth_header"],
                "auth_prefix": p["auth_prefix"],
                "doc_url": p["doc_url"],
                "signup_url": p["signup_url"],
                "models": [
                    {
                        "id": m["id"],
                        "name": m["name"],
                        "description": m.get("description", ""),
                        "context_window": m.get("context_window", 0),
                        "max_output": m.get("max_output", 0),
                        "supports_streaming": m.get("supports_streaming", True),
                        "supports_vision": m.get("supports_vision", False),
                        "supports_tools": m.get("supports_tools", False),
                        "tags": m.get("tags", []),
                    }
                    for m in p["models"]
                ],
            }
            for p in PROVIDERS
        ]
    }
